AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds/*'
Metrics/LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 16

Metrics/BlockNesting:
  Max: 4
