version: '2'
services:
  db:
    image: 'postgres:10.5'
    volumes:
      - ~/piubs_data/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    env_file:
      - config/.env
    volumes:
      - .:/var/www/PIUBS
      - ~/backups:/root/backups
    expose:
      - "3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml --environment production
    env_file:
      - config/.env
    depends_on:
      - redis
    volumes:
      - .:/var/www/PIUBS

  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - app
    ports:
      - "8081:80"
