toolbar:
  - styleselect bold italic | undo redo | image link | emoticons | forecolor backcolor | preview restoredraft
menubar:
  - view
plugins:
  - image
  - link
  - autolink
  - autosave
  - wordcount
  - emoticons
  - preview
  - textcolor
  - paste
paste_as_text: true
link_assume_external_targets: true
default_link_target: _blank
