# frozen_string_literal: true

class CreateCategories < ActiveRecord::Migration[5.2]
  def self.up
    create_table :TB_CATEGORIA, id: false do |t|
      t.bigint :CO_SEQ_ID
      t.string :NO_NOME, null: false
      t.bigint :CO_CATEGORIA_PAI
      t.integer :NU_PROFUNDIDADE, default: 0
      t.integer :NU_SEVERIDADE, null: false
      t.bigint :CO_SISTEMA_ORIGEM, null: false
    end

    execute <<-SQL
      CREATE SEQUENCE "SQ_CATEGORIA_ID";

      ALTER TABLE "TB_CATEGORIA" ADD CONSTRAINT "PK_TB_CATEGORIA" PRIMARY KEY ("CO_SEQ_ID");

      ALTER TABLE "TB_CATEGORIA" ALTER COLUMN "CO_SEQ_ID" SET DEFAULT nextval('"SQ_CATEGORIA_ID"');

      ALTER SEQUENCE "SQ_CATEGORIA_ID" OWNED BY "TB_CATEGORIA"."CO_SEQ_ID";

      ALTER TABLE "TB_CATEGORIA" ADD CONSTRAINT "FK_CATEGORIA_CATEGORIA" FOREIGN KEY ("CO_CATEGORIA_PAI")
        REFERENCES "TB_CATEGORIA" ("CO_SEQ_ID") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "TB_CATEGORIA" ADD CONSTRAINT "FK_SISTEMA_CATEGORIA" FOREIGN KEY ("CO_SISTEMA_ORIGEM")
        REFERENCES "TB_SISTEMA" ("CO_SEQ_ID") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;
    SQL
  end

  def self.down
    execute <<-SQL
      ALTER TABLE "TB_CATEGORIA" DROP CONSTRAINT "PK_TB_CATEGORIA";
      ALTER TABLE "TB_CATEGORIA" DROP CONSTRAINT "FK_CATEGORIA_CATEGORIA";
      ALTER TABLE "TB_CATEGORIA" DROP CONSTRAINT "FK_SISTEMA_CATEGORIA";
    SQL
    drop_table :TB_CATEGORIA
  end
end
