# frozen_string_literal: true

class CreateCalls < ActiveRecord::Migration[5.2]
  def self.up
    create_table :TB_ATENDIMENTO, id: false do |t|
      t.bigint :CO_PROTOCOLO, null: false
      t.string :DS_TITULO, null: false
      t.text :DS_DESCRICAO, null: false
      t.integer :TP_STATUS, null: false, default: 0 # Open!
      t.string :DS_VERSAO_SISTEMA
      t.string :DS_PERFIL_ACESSO
      t.string :DS_DETALHE_FUNCIONALIDADE
      t.bigint :CO_CIDADE, null: false
      t.integer :CO_CATEGORIA, null: false
      t.bigint :CO_SEI, null: false
      t.datetime :DT_CRIADO_EM
      t.bigint :CO_USUARIO_EMPRESA, null: false
      t.bigint :CO_RESPOSTA
      t.bigint :CO_CNES
      t.bigint :CO_USUARIO_SUPORTE
      t.integer :NU_SEVERIDADE, default: 1 # Severidade normal
      t.datetime :DT_FINALIZADO_EM
      t.datetime :DT_REABERTO_EM
    end

    execute <<-SQL
      ALTER TABLE "TB_ATENDIMENTO" ADD CONSTRAINT "PK_TB_ATENDIMENTO" PRIMARY KEY ("CO_PROTOCOLO");

      ALTER TABLE "TB_ATENDIMENTO" ADD CONSTRAINT "FK_EMPRESA_ATENDIMENTO" FOREIGN KEY ("CO_SEI")
        REFERENCES "TB_EMPRESA" ("CO_SEI") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "TB_ATENDIMENTO" ADD CONSTRAINT "FK_QUESTAO_ATENDIMENTO" FOREIGN KEY ("CO_RESPOSTA")
        REFERENCES "TB_QUESTAO" ("CO_SEQ_ID") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "TB_ATENDIMENTO" ADD CONSTRAINT "FK_USUARIO_ATENDIMENTO_USUARIO_SUPORTE" FOREIGN KEY ("CO_USUARIO_SUPORTE")
        REFERENCES "TB_USUARIO" (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "TB_ATENDIMENTO" ADD CONSTRAINT "FK_CIDADE_ATENDIMENTO" FOREIGN KEY ("CO_CIDADE")
        REFERENCES "TB_CIDADE" ("CO_CODIGO") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "TB_ATENDIMENTO" ADD CONSTRAINT "FK_CATEGORIA_ATENDIMENTO" FOREIGN KEY ("CO_CATEGORIA")
        REFERENCES "TB_CATEGORIA" ("CO_SEQ_ID") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "TB_ATENDIMENTO" ADD CONSTRAINT "FK_USUARIO_ATENDIMENTO_USUARIO_EMPRESA" FOREIGN KEY ("CO_USUARIO_EMPRESA")
        REFERENCES "TB_USUARIO" (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "TB_ATENDIMENTO" ADD CONSTRAINT "FK_UBS_ATENDIMENTO" FOREIGN KEY ("CO_CNES")
        REFERENCES "TB_UBS" ("CO_CNES") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;
    SQL
  end

  def self.down
    execute <<-SQL
      ALTER TABLE "TB_ATENDIMENTO" DROP CONSTRAINT "PK_TB_ATENDIMENTO";
      ALTER TABLE "TB_ATENDIMENTO" DROP CONSTRAINT "FK_EMPRESA_ATENDIMENTO";
      ALTER TABLE "TB_ATENDIMENTO" DROP CONSTRAINT "FK_QUESTAO_ATENDIMENTO";
      ALTER TABLE "TB_ATENDIMENTO" DROP CONSTRAINT "FK_USUARIO_ATENDIMENTO_USUARIO_SUPORTE";
      ALTER TABLE "TB_ATENDIMENTO" DROP CONSTRAINT "FK_CIDADE_ATENDIMENTO";
      ALTER TABLE "TB_ATENDIMENTO" DROP CONSTRAINT "FK_CATEGORIA_ATENDIMENTO";
      ALTER TABLE "TB_ATENDIMENTO" DROP CONSTRAINT "FK_USUARIO_ATENDIMENTO_USUARIO_EMPRESA";
      ALTER TABLE "TB_ATENDIMENTO" DROP CONSTRAINT "FK_UBS_ATENDIMENTO";
    SQL
    drop_table :TB_ATENDIMENTO
  end
end
