# frozen_string_literal: true

class CreateAttachmentsLinks < ActiveRecord::Migration[5.2]
  def self.up
    create_table :RT_LINK_ANEXO, id: false do |t|
      t.uuid :CO_ID, null: false, default: 'uuid_generate_v4()'
      t.uuid :CO_ANEXO, null: false
      t.bigint :CO_RESPOSTA
      t.bigint :CO_ATENDIMENTO
      t.bigint :CO_QUESTAO
      t.bigint :CO_CONTROVERSIA
      t.bigint :CO_FEEDBACK
      t.bigint :TP_ENTIDADE_ORIGEM, null: false
      t.datetime :DT_CRIADO_EM
    end

    execute <<-SQL
      -- FK
      ALTER TABLE "RT_LINK_ANEXO" ADD CONSTRAINT "FK_ANEXO_LINK_ANEXO" FOREIGN KEY ("CO_ANEXO")
        REFERENCES "TB_ANEXO" ("CO_ID") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "RT_LINK_ANEXO" ADD CONSTRAINT "FK_ATENDIMENTO_LINK_ANEXO" FOREIGN KEY ("CO_ATENDIMENTO")
        REFERENCES "TB_ATENDIMENTO" ("CO_PROTOCOLO") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "RT_LINK_ANEXO" ADD CONSTRAINT "FK_FEEDBACK_LINK_ANEXO" FOREIGN KEY ("CO_FEEDBACK")
        REFERENCES "TB_FEEDBACK" ("CO_PROTOCOLO") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "RT_LINK_ANEXO" ADD CONSTRAINT "FK_RESPOSTA_LINK_ANEXO" FOREIGN KEY ("CO_RESPOSTA")
        REFERENCES "TB_RESPOSTA" ("CO_ID") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "RT_LINK_ANEXO" ADD CONSTRAINT "FK_CONTROVERSIA_LINK_ANEXO" FOREIGN KEY ("CO_CONTROVERSIA")
        REFERENCES "TB_CONTROVERSIA" ("CO_PROTOCOLO") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;

      ALTER TABLE "RT_LINK_ANEXO" ADD CONSTRAINT "FK_QUESTAO_LINK_ANEXO" FOREIGN KEY ("CO_QUESTAO")
        REFERENCES "TB_QUESTAO" ("CO_SEQ_ID") MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION;
    SQL
  end

  def self.down
    execute <<-SQL
      ALTER TABLE "RT_LINK_ANEXO" DROP CONSTRAINT "FK_ANEXO_LINK_ANEXO";
      ALTER TABLE "RT_LINK_ANEXO" DROP CONSTRAINT "FK_ATENDIMENTO_LINK_ANEXO";
      ALTER TABLE "RT_LINK_ANEXO" DROP CONSTRAINT "FK_FEEDBACK_LINK_ANEXO";
      ALTER TABLE "RT_LINK_ANEXO" DROP CONSTRAINT "FK_RESPOSTA_LINK_ANEXO";
      ALTER TABLE "RT_LINK_ANEXO" DROP CONSTRAINT "FK_CONTROVERSIA_LINK_ANEXO";
      ALTER TABLE "RT_LINK_ANEXO" DROP CONSTRAINT "FK_QUESTAO_LINK_ANEXO";
    SQL

    drop_table :RT_LINK_ANEXO
  end
end
